### PR TITLE
Branch fix bugs

### LINKED ISSUE #64: Member / Sessions equal up to case should not be distinct

### PR DESCRIPTION
**Pull request by starchypotatocode**
Fix #64

### CODE REVIEW

File: src/main/java/hallpointer/address/logic/commands/DeleteSessionCommand.java [hunk 1]
```diff
@@ -35,15 +39,16 @@ public class DeleteSessionCommand extends Command {
     public static final String MESSAGE_INVALID_INDEX = "Error: Invalid index specified.";
     public static final String MESSAGE_DELETE_SESSION_FAIL = "Error: Session %1$s does not exist in member %2$s.";
 
-    private final List<Index> memberIndexes;
+    private final Set<Index> memberIndexes;
```
Comment (yuvrajaryan) [inline src/main/java/hallpointer/address/logic/commands/DeleteSessionCommand.java:42]: Good use of defensive coding

**Review by yuvrajaryan — COMMENTED** [review]
LGTM. Can merge.
