### PR TITLE
Add tests & Fix Bugs

### LINKED ISSUE #86: Ensure UI refreshes upon adding session without further action required

### PR DESCRIPTION
**Pull request by starchypotatocode**
Fix #86, #85, #67 

(Might have introduced regressions in storage unfortunately)

### CODE REVIEW

File: src/main/java/hallpointer/address/model/point/Point.java [hunk 1]
```diff
@@ -5,19 +5,21 @@
...
- * Guarantees: immutable; points are valid as declared in {@link #isValidPoints(int)}
+ * Guarantees: immutable; points are valid as declared in {@link #isValidPoints(String)}
  */
 public class Point {
 
     public static final String MESSAGE_CONSTRAINTS = "Points must be a non-negative integer.";
-    public final int points;
+
+    public static final String VALIDATION_REGEX = "^\\d+$";
+    public final String points;
```
Comment (QinHaichen12) [inline src/main/java/hallpointer/address/model/point/Point.java:15]: why do we change points to String representation here?

**Review by QinHaichen12 — COMMENTED** [review]
LGTM! Will be merged.
